/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import com.finbourne.access.model.DateUnit;
import com.finbourne.access.model.PointInTimeSpecification;
import com.finbourne.access.model.RelativeToDateTime;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EffectiveDateRelative
 */
public class EffectiveDateRelativeTest {
    private final EffectiveDateRelative model = new EffectiveDateRelative();

    /**
     * Model tests for EffectiveDateRelative
     */
    @Test
    public void testEffectiveDateRelative() {
        // TODO: test EffectiveDateRelative
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'adjustment'
     */
    @Test
    public void adjustmentTest() {
        // TODO: test adjustment
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

    /**
     * Test the property 'relativeToDateTime'
     */
    @Test
    public void relativeToDateTimeTest() {
        // TODO: test relativeToDateTime
    }

}
