/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import com.finbourne.access.model.AsAtRangeForSpec;
import com.finbourne.access.model.AsAtRelative;
import com.finbourne.access.model.EffectiveDateHasQuality;
import com.finbourne.access.model.EffectiveDateRelative;
import com.finbourne.access.model.EffectiveRange;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForSpec
 */
public class ForSpecTest {
    private final ForSpec model = new ForSpec();

    /**
     * Model tests for ForSpec
     */
    @Test
    public void testForSpec() {
        // TODO: test ForSpec
    }

    /**
     * Test the property 'asAtRangeForSpec'
     */
    @Test
    public void asAtRangeForSpecTest() {
        // TODO: test asAtRangeForSpec
    }

    /**
     * Test the property 'asAtRelative'
     */
    @Test
    public void asAtRelativeTest() {
        // TODO: test asAtRelative
    }

    /**
     * Test the property 'effectiveDateHasQuality'
     */
    @Test
    public void effectiveDateHasQualityTest() {
        // TODO: test effectiveDateHasQuality
    }

    /**
     * Test the property 'effectiveDateRelative'
     */
    @Test
    public void effectiveDateRelativeTest() {
        // TODO: test effectiveDateRelative
    }

    /**
     * Test the property 'effectiveRange'
     */
    @Test
    public void effectiveRangeTest() {
        // TODO: test effectiveRange
    }

}
