/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import com.finbourne.access.model.TextOperator;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IfIdentityClaimExpression
 */
public class IfIdentityClaimExpressionTest {
    private final IfIdentityClaimExpression model = new IfIdentityClaimExpression();

    /**
     * Model tests for IfIdentityClaimExpression
     */
    @Test
    public void testIfIdentityClaimExpression() {
        // TODO: test IfIdentityClaimExpression
    }

    /**
     * Test the property 'claimType'
     */
    @Test
    public void claimTypeTest() {
        // TODO: test claimType
    }

    /**
     * Test the property 'claimValueType'
     */
    @Test
    public void claimValueTypeTest() {
        // TODO: test claimValueType
    }

    /**
     * Test the property 'claimIssuer'
     */
    @Test
    public void claimIssuerTest() {
        // TODO: test claimIssuer
    }

    /**
     * Test the property 'claimOriginalIssuer'
     */
    @Test
    public void claimOriginalIssuerTest() {
        // TODO: test claimOriginalIssuer
    }

    /**
     * Test the property 'operator'
     */
    @Test
    public void operatorTest() {
        // TODO: test operator
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
