/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import com.finbourne.access.model.ActionId;
import com.finbourne.access.model.SelectorDefinition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PolicySelectorDefinition
 */
public class PolicySelectorDefinitionTest {
    private final PolicySelectorDefinition model = new PolicySelectorDefinition();

    /**
     * Model tests for PolicySelectorDefinition
     */
    @Test
    public void testPolicySelectorDefinition() {
        // TODO: test PolicySelectorDefinition
    }

    /**
     * Test the property 'identityRestriction'
     */
    @Test
    public void identityRestrictionTest() {
        // TODO: test identityRestriction
    }

    /**
     * Test the property 'restrictionSelectors'
     */
    @Test
    public void restrictionSelectorsTest() {
        // TODO: test restrictionSelectors
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
