/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import com.finbourne.access.model.ForSpec;
import com.finbourne.access.model.Grant;
import com.finbourne.access.model.HowSpec;
import com.finbourne.access.model.IfExpression;
import com.finbourne.access.model.SelectorDefinition;
import com.finbourne.access.model.WhenSpec;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PolicyCreationRequest
 */
public class PolicyCreationRequestTest {
    private final PolicyCreationRequest model = new PolicyCreationRequest();

    /**
     * Model tests for PolicyCreationRequest
     */
    @Test
    public void testPolicyCreationRequest() {
        // TODO: test PolicyCreationRequest
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'applications'
     */
    @Test
    public void applicationsTest() {
        // TODO: test applications
    }

    /**
     * Test the property 'grant'
     */
    @Test
    public void grantTest() {
        // TODO: test grant
    }

    /**
     * Test the property 'selectors'
     */
    @Test
    public void selectorsTest() {
        // TODO: test selectors
    }

    /**
     * Test the property '_for'
     */
    @Test
    public void _forTest() {
        // TODO: test _for
    }

    /**
     * Test the property '_if'
     */
    @Test
    public void _ifTest() {
        // TODO: test _if
    }

    /**
     * Test the property 'when'
     */
    @Test
    public void whenTest() {
        // TODO: test when
    }

    /**
     * Test the property 'how'
     */
    @Test
    public void howTest() {
        // TODO: test how
    }

}
