/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import com.finbourne.access.model.PolicyCollectionId;
import com.finbourne.access.model.PolicyId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RemoveFromPolicyCollectionRequest
 */
public class RemoveFromPolicyCollectionRequestTest {
    private final RemoveFromPolicyCollectionRequest model = new RemoveFromPolicyCollectionRequest();

    /**
     * Model tests for RemoveFromPolicyCollectionRequest
     */
    @Test
    public void testRemoveFromPolicyCollectionRequest() {
        // TODO: test RemoveFromPolicyCollectionRequest
    }

    /**
     * Test the property 'policies'
     */
    @Test
    public void policiesTest() {
        // TODO: test policies
    }

    /**
     * Test the property 'policyCollections'
     */
    @Test
    public void policyCollectionsTest() {
        // TODO: test policyCollections
    }

}
