/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import com.finbourne.access.model.RequestedActionKey;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RequestDetails
 */
public class RequestDetailsTest {
    private final RequestDetails model = new RequestDetails();

    /**
     * Model tests for RequestDetails
     */
    @Test
    public void testRequestDetails() {
        // TODO: test RequestDetails
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'fromEffectiveDate'
     */
    @Test
    public void fromEffectiveDateTest() {
        // TODO: test fromEffectiveDate
    }

    /**
     * Test the property 'toEffectiveDate'
     */
    @Test
    public void toEffectiveDateTest() {
        // TODO: test toEffectiveDate
    }

    /**
     * Test the property 'fromAsAt'
     */
    @Test
    public void fromAsAtTest() {
        // TODO: test fromAsAt
    }

    /**
     * Test the property 'toAsAt'
     */
    @Test
    public void toAsAtTest() {
        // TODO: test toAsAt
    }

}
