/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import com.finbourne.access.model.NonTransitiveSupervisorRoleResource;
import com.finbourne.access.model.PolicyIdRoleResource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RoleResourceRequest
 */
public class RoleResourceRequestTest {
    private final RoleResourceRequest model = new RoleResourceRequest();

    /**
     * Model tests for RoleResourceRequest
     */
    @Test
    public void testRoleResourceRequest() {
        // TODO: test RoleResourceRequest
    }

    /**
     * Test the property 'nonTransitiveSupervisorRoleResource'
     */
    @Test
    public void nonTransitiveSupervisorRoleResourceTest() {
        // TODO: test nonTransitiveSupervisorRoleResource
    }

    /**
     * Test the property 'policyIdRoleResource'
     */
    @Test
    public void policyIdRoleResourceTest() {
        // TODO: test policyIdRoleResource
    }

}
