/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import com.finbourne.access.model.IdSelectorDefinition;
import com.finbourne.access.model.MatchAllSelectorDefinition;
import com.finbourne.access.model.MetadataSelectorDefinition;
import com.finbourne.access.model.PolicySelectorDefinition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SelectorDefinition
 */
public class SelectorDefinitionTest {
    private final SelectorDefinition model = new SelectorDefinition();

    /**
     * Model tests for SelectorDefinition
     */
    @Test
    public void testSelectorDefinition() {
        // TODO: test SelectorDefinition
    }

    /**
     * Test the property 'metadataSelectorDefinition'
     */
    @Test
    public void metadataSelectorDefinitionTest() {
        // TODO: test metadataSelectorDefinition
    }

    /**
     * Test the property 'idSelectorDefinition'
     */
    @Test
    public void idSelectorDefinitionTest() {
        // TODO: test idSelectorDefinition
    }

    /**
     * Test the property 'matchAllSelectorDefinition'
     */
    @Test
    public void matchAllSelectorDefinitionTest() {
        // TODO: test matchAllSelectorDefinition
    }

    /**
     * Test the property 'policySelectorDefinition'
     */
    @Test
    public void policySelectorDefinitionTest() {
        // TODO: test policySelectorDefinition
    }

}
