/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.1950
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.api;

import com.finbourne.access.ApiException;
import com.finbourne.access.model.LusidProblemDetails;
import com.finbourne.access.model.ResourceListOfAccessControlledResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApplicationMetadataApi
 */
@Ignore
public class ApplicationMetadataApiTest {

    private final ApplicationMetadataApi api = new ApplicationMetadataApi();

    
    /**
     * [EARLY ACCESS] ListAccessControlledResources: Get resources available for access control
     *
     * Get the comprehensive set of resources that are available for access control
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccessControlledResourcesTest() throws ApiException {
        ResourceListOfAccessControlledResource response = api.listAccessControlledResources();

        // TODO: test validations
    }
    
}
