/*
 * FINBOURNE Access Management API
 * ### Introduction    This page documents the LUSID Access Management APIs from FINBOURNE Technology, which allow authorised users to query and update their access control policies and roles within the LUSID platform's Identity and Access Management system.    
 *
 * The version of the OpenAPI document: 0.0.3031
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.access.model;

import java.util.Objects;
import java.util.Arrays;
import com.finbourne.access.model.TextOperator;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IfIdentityClaimExpression
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IfIdentityClaimExpression {
  public static final String SERIALIZED_NAME_CLAIM_TYPE = "claimType";
  @SerializedName(SERIALIZED_NAME_CLAIM_TYPE)
  private String claimType;

  public static final String SERIALIZED_NAME_CLAIM_VALUE_TYPE = "claimValueType";
  @SerializedName(SERIALIZED_NAME_CLAIM_VALUE_TYPE)
  private String claimValueType;

  public static final String SERIALIZED_NAME_CLAIM_ISSUER = "claimIssuer";
  @SerializedName(SERIALIZED_NAME_CLAIM_ISSUER)
  private String claimIssuer;

  public static final String SERIALIZED_NAME_CLAIM_ORIGINAL_ISSUER = "claimOriginalIssuer";
  @SerializedName(SERIALIZED_NAME_CLAIM_ORIGINAL_ISSUER)
  private String claimOriginalIssuer;

  public static final String SERIALIZED_NAME_OPERATOR = "operator";
  @SerializedName(SERIALIZED_NAME_OPERATOR)
  private TextOperator operator;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;


  public IfIdentityClaimExpression claimType(String claimType) {
    this.claimType = claimType; 
    return this;
  }

   /**
   * Get claimType
   * @return claimType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getClaimType() {
    return claimType;
  }

  public void setClaimType(String claimType) {
    this.claimType = claimType;
  }


  public IfIdentityClaimExpression claimValueType(String claimValueType) {
    this.claimValueType = claimValueType; 
    return this;
  }

   /**
   * Get claimValueType
   * @return claimValueType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getClaimValueType() {
    return claimValueType;
  }

  public void setClaimValueType(String claimValueType) {
    this.claimValueType = claimValueType;
  }


  public IfIdentityClaimExpression claimIssuer(String claimIssuer) {
    this.claimIssuer = claimIssuer; 
    return this;
  }

   /**
   * Get claimIssuer
   * @return claimIssuer
  **/
  @ApiModelProperty(value = "")
  public String getClaimIssuer() {
    return claimIssuer;
  }

  public void setClaimIssuer(String claimIssuer) {
    this.claimIssuer = claimIssuer;
  }


  public IfIdentityClaimExpression claimOriginalIssuer(String claimOriginalIssuer) {
    this.claimOriginalIssuer = claimOriginalIssuer; 
    return this;
  }

   /**
   * Get claimOriginalIssuer
   * @return claimOriginalIssuer
  **/
  @ApiModelProperty(value = "")
  public String getClaimOriginalIssuer() {
    return claimOriginalIssuer;
  }

  public void setClaimOriginalIssuer(String claimOriginalIssuer) {
    this.claimOriginalIssuer = claimOriginalIssuer;
  }


  public IfIdentityClaimExpression operator(TextOperator operator) {
    this.operator = operator; 
    return this;
  }

   /**
   * Get operator
   * @return operator
  **/
  @ApiModelProperty(required = true, value = "")
  public TextOperator getOperator() {
    return operator;
  }

  public void setOperator(TextOperator operator) {
    this.operator = operator;
  }


  public IfIdentityClaimExpression value(String value) {
    this.value = value; 
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IfIdentityClaimExpression {\n");
    sb.append("    claimType: ").append(toIndentedString(claimType)).append("\n");
    sb.append("    claimValueType: ").append(toIndentedString(claimValueType)).append("\n");
    sb.append("    claimIssuer: ").append(toIndentedString(claimIssuer)).append("\n");
    sb.append("    claimOriginalIssuer: ").append(toIndentedString(claimOriginalIssuer)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
